### PR TITLE
Fix selecting channel error.

### PR DESCRIPTION
**Pull request by noamsto**
Switched from using beautifulsoup to xmltodict.
Beautifulsoup couldn't parse properly eco99fm RSS and resulted with missing <\link> tag.

### CODE REVIEW

**Comment by nire0510** [comment]
Hi @noamsto , thank you for your PR 👍
Can you tell why you had to replace BeautifulSoup? Is there any documentation online states that BeautifulSoup is no longer supported in Kodi?

**Comment by noamsto** [comment]
BeautifulSoup is still supported in Kodi. But for it to work properly we need to pass "xml" to it's builder. i.e: `BeautifulSoup(page_src, "xml")` . For this to work we need [lxml library](https://lxml.de/) which is not officialy supported by Kodi.
Converting the parser to [xmltodict](https://github.com/martinblech/xmltodict) seems like the simplest solution so far.

**Comment by nire0510** [comment]
@noamsto thank for clarifying, but basically you can just add lxml as a dependency in the addon manifest, and it should work, w/o changing the code at all. Didn't it work for you?

**Comment by noamsto** [comment]
I double checked it and unfortunately it's not working. For this to work we need `lxml` library and as i stated it's not available in Kodi. It could save some headache (and improve performance) if we had this library, but since it's not available i had to work with what we have. `xmltodict` :)

**Comment by nire0510** [comment]
@noamsto I'll take your word for that :)
Merging PR - you may now resubmit this repo to Kodi's official repo. Make sure you read carefully their instructions if you want it to end in a reasonable time ;)

**Pull request merged**
